{% set name = "xrt" %}
{% set version = "1.3.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.zip
  sha256: 0ca221e95a4fd5218e62094c35e25bab15d13f5562b410fe7348ae8a338696bc
  # TODO: remove the patch after https://github.com/kklmn/xrt/pull/42 is accepted/merged/released.
  patches:
    - entry-points.patch

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  skip: true  # [py<36]
  entry_points:
    - {{ name }} = {{ name }}.gui.xrtQookStart:main

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
  run:
    - python
    - matplotlib
    - numpy
    - pyqt
    - scipy
    - sphinx
    # - pyopencl  - Not sure if we need this (optional runtime dep)

test:
  imports:
    - xrt
    - xrt.backends
    - xrt.backends.raycing
    - xrt.gui
    - xrt.gui.commons
    - xrt.gui.xrtGlow
    - xrt.gui.xrtQook
  commands:
    - which xrt  # [not win]
    - where xrt  # [win]

about:
  home: https://xrt.readthedocs.io
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Ray tracing and wave propagation in x-ray regime
  description: |
    Package xrt (XRayTracer) is a python software library for ray tracing and
    wave propagation in x-ray regime. It is primarily meant for modeling
    synchrotron sources, beamlines and beamline elements. Includes a GUI for
    creating a beamline and interactively viewing it in 3D.
  doc_url: https://xrt.readthedocs.io
  dev_url: https://github.com/kklmn/xrt
